name: Docker Image (Link)

on:
  push:
    branches: [main]
    paths:
      - "mrx-link/Dockerfile"
      - "mrx-link/requirements.txt"
  workflow_dispatch:

jobs:
  build-push:
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"

    name: Build mrx-link image (Python ${{ matrix.python }})
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ORG_PAT }}
          fetch-depth: 0
          lfs: true
          submodules: true
      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ORG_PAT }}
      - name: Build and push mrx-link
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./mrx-link
          file: ./mrx-link/Dockerfile
          tags: |
            ghcr.io/makinarocks/mrx-link:1.0.0-python${{ matrix.python }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_IMAGE=ghcr.io/makinarocks/mrx-link-base:python${{ matrix.python }}
